<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
    <NoWarn>NU1701</NoWarn>
    <DefaultItemExcludes>$(DefaultItemExcludes);Tests\**;Tests\**\*</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*" />
    <EmbeddedResource Remove="Tests\**\*" />
    <None Remove="Tests\**\*" />
    <Page Remove="Tests\**\*" />
    <ApplicationDefinition Remove="Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*" />
  </ItemGroup>

</Project>
